image: ubuntu:20.04

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - apt-get update  --yes
  - apt-get upgrade --yes
  - DEBIAN_FRONTEND=noninteractive apt-get install --yes cmake
  - apt-get install --yes build-essential
  - apt-get install --yes libgl1-mesa-dev
  - apt-get install --yes libxt-dev
  - apt-get install --yes libxrandr-dev
  - apt-get install --yes libxinerama-dev
  - apt-get install --yes libxcursor-dev
  - apt-get install --yes libxi-dev
  - apt-get install --yes libglew-dev

build:
  script:
  - cp override_pmp_files/SurfaceMeshGL.cpp externals/pmp-library/src/pmp/visualization/SurfaceMeshGL.cpp
  - cd ./externals/pmp-library/
  - mkdir build
  - cd build
  - cmake -S ../ -B ./
  - cmake --build ./
  - cd ../../../
  - mkdir build
  - cd build
  - cmake -S ../ -B ./
  - cmake --build ./
  - mkdir ../artifacts
  - cp ./tps/tp* ../artifacts/
  artifacts:
    paths:
      - artifacts
