image: alpine

pages:
  script:
    - apk update && apk add doxygen && apk add graphviz
    - doxygen doc/Doxyfile
    - mv doc/html/ public/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
