image: alpine

pages:
  script:
    - cd doc
    - apk update && apk add doxygen
    - doxygen -u Doxyfile
    - doxygen Doxyfile
    - cd ..
    - mv doc/html/ public/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
