image: ubuntu:20.04

pages:
  script:
    - sudo aptitude install graphviz doxygen
    - doxygen doc/Doxyfile
    - mv doc/html/ public/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
