image: ubuntu:20.04

before_script:
  - apt-get update  --yes
  - apt-get upgrade --yes
  - DEBIAN_FRONTEND=noninteractive apt-get install --yes cmake

build:
  script:
  - mkdir build
  - cd build
  - cmake -S ../ -B ./
  - cmake --build ./
